In [1]:
import numpy as np
import random

In [2]:
def calcCombinations():
    allConfigs = []
    n = 1
    while len(allConfigs) < 16:
        config = []
        for i in range(4):
            config.append(random.choice([1,-1]))
        if config not in allConfigs:
            n += 1
            allConfigs.append(config)
    print(f"It took {n} iterations to get all combinations")
    print(allConfigs)
    return allConfigs

In [3]:
combConfigs = calcCombinations()

It took 17 iterations to get all combinations
[[1, 1, -1, 1], [-1, 1, 1, -1], [1, 1, 1, 1], [-1, 1, -1, -1], [-1, -1, 1, 1], [-1, 1, -1, 1], [-1, -1, 1, -1], [1, -1, -1, 1], [-1, -1, -1, -1], [-1, 1, 1, 1], [1, -1, 1, 1], [-1, -1, -1, 1], [1, 1, -1, -1], [1, -1, 1, -1], [1, -1, -1, -1], [1, 1, 1, -1]]


In [7]:
Rmatrix_empty = [[0 for x in range(16)] for y in range(16)]

In [6]:
def check_R_condition(vec1, vec2):
    return (vec1[0] != vec2[0]) and (vec1[1] != vec2[1]) and (vec1[2] != vec2[2]) and vec1[3] != vec2[3]

In [9]:
def construct_R(matrix):
    for i, row in enumerate(combConfigs):
        for j, col in enumerate(combConfigs):
            if check_R_condition(row, col):
                matrix[i][j] = 1
    return matrix

In [12]:
Rmatrix = construct_R(Rmatrix_empty)

[[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]] 16


In [15]:
print('R = \n',np.array(Rmatrix))

R = 
 [[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]]
